version: '3'
services:
    rstudio:
        env_file: .env
        build:
            context: .
        environment:
            - TZ=Asia/Tokyo
        ports:
            - "8787:8787"
        volumes:
            - .:/home/rstudio/work
